### ISSUE TITLE
`nscd` fails to start on ubuntu 12.04 as `nscd` user does not exist there by default

### ISSUE THREAD

**Issue by dtoubelis** [chef-cookbooks/nscd#10]
The template that creates `/etc/nscd.conf` sets `server-user` equals `nscd` however, `nscd` user does not exist on ubuntu 12.04 by default. So, this recipe needs either to make sure that `nscd` user exists or use `root` as a better default.

The fact that `nscd` is unable to start is not that big of a problem by itself, however other cookbooks that use `execute[nscd-clear-passwd]` and `execute[nscd-clear-shadow]` calls fail because of this problem. `openldap::auth` is a notable example.

**Comment by lamont-granquist** [comment]
+1

related PR seems to be here: #12

**Comment by glensc** [comment]
#12 seem to lack CLA sign, at least @TheFurya has not responded there he has signed it

**Comment by lamont-granquist** [comment]
Yeah, I'm not positive that's the right way to solve it.  I just added creating the user to my wrapper cookbook and moved on though...

**Comment by glensc** [comment]
yup. it has small chance of merging as it contains changes to more than one area (some package name changes) and of course `node.override` which shouldn't be used in cookbooks.
