### ISSUE TITLE
incomplete sentence

### ISSUE THREAD

**Issue by glensc** [chef-cookbooks/nscd#16]
![image](https://cloud.githubusercontent.com/assets/199095/13118791/a3a019aa-d5ae-11e5-930f-90afdb2c7d2a.png)

**Comment by glensc** [comment]
also would be nice to know what exactly is broken or missing if i use 2.0 cookbook under chef < 12

and chef version is meant version of chef-client or the chef-server?

**Comment by iennae** [comment]
@glensc thanks for reporting this issue. I've updated the README to fix for your first comment about the dangling sentence. 

For your second comment, Chef 12 is in reference to chef running on the local node, i.e. chef-client. As mentioned earlier in the README the clear_cache resource was created. This resource is defined in specifically a 12+ manner where there is not a separate provider as well. You won't be able to use the clear_cache resource on a node with less than Chef 12.
