### ISSUE TITLE
Debian doesn't know how to disable 'database netgroup'

### ISSUE THREAD

**Issue by kplimack** [chef-cookbooks/nscd#6]
root@use1d-build101:~# nscd -f /etc/nscd.conf
nscd: database netgroup is not supported
nscd: database netgroup is not supported
nscd: database netgroup is not supported
nscd: database netgroup is not supported
nscd: database netgroup is not supported
nscd: database netgroup is not supported
nscd: database netgroup is not supported
nscd: database netgroup is not supported

# netgroup database
enable-cache		netgroup	no
positive-time-to-live		netgroup	28800
negative-time-to-live		netgroup	20
suggested-size		netgroup	211
check-files		netgroup	yes
persistent		netgroup	yes
shared		netgroup	yes
max-db-size		netgroup	33554432

**Comment by tas50** [comment]
3.0 now removes the unsupported databases automatically.  That should resolve your problem for you.
