### ISSUE TITLE
Unscd service name is unscd, not nscd

### ISSUE THREAD

**Issue by hannesg** [chef-cookbooks/nscd#8]
Hi

I've tried to use this cookbook with the unscd package from debian/ubuntu. The packages contain a nscd binary but the service name is unscd ( See https://packages.debian.org/wheezy/amd64/unscd/filelist for example ).

Cheers
Hannes

**Comment by iennae** [comment]
@glensc As I mentioned in my PR that I have since closed, please go ahead and submit your updates as a current PR (make sure rebased to current cookbook, and signed commits with DCO). Thanks!
